version: '3.9'
services:
  db:
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default
    volumes:
    - ./migrations:/docker-entrypoint-initdb.d
